workflows:
  ios-kmp-build:
    name: Build iOS for KMP
    environment:
      vars:
        XCODE_WORKSPACE: "iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
        BUNDLE_ID: "com.example.kmpapp"
        APP_STORE_CONNECT_KEY_ID: Encrypted(...) # opcional para deploy
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean build folders
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          ./gradlew clean
      - name: Install dependencies
        script: |
          cd iosApp
          pod install
      - name: Build iOS app
        script: |
          xcodebuild build \
            -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS'
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
