workflows:
  ios-kmp-build:
    name: Build iOS for KMP
    environment:
      vars:
        XCODE_PROJECT: "iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
      xcode: latest
      cocoapods: default
      signing:
        xcode: automatic  # Automatic signing pelo Codemagic
    scripts:
      - name: Clean build
        script: |
          xcodebuild clean -project $XCODE_PROJECT -scheme $XCODE_SCHEME
      - name: Archive app
        script: |
          xcodebuild archive \
            -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/ios/iosApp.xcarchive
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/iosApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
